using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Globalization;
using UnityEngine;

namespace IFCImporter
{
    /// <summary>
    /// Parses CSV metadata files generated by the Python IFC exporter.
    /// </summary>
    public static class CsvMetadataParser
    {
        /// <summary>
        /// Parse a CSV file and return element data.
        /// </summary>
        public static List<IfcElementData> ParseCsvFile(string filePath)
        {
            var elements = new List<IfcElementData>();

            if (!File.Exists(filePath))
            {
                Debug.LogError($"CSV file not found: {filePath}");
                return elements;
            }

            try
            {
                var lines = File.ReadAllLines(filePath, Encoding.UTF8);
                if (lines.Length < 2)
                {
                    Debug.LogWarning("CSV file is empty or has no data rows");
                    return elements;
                }

                // Parse header
                var headers = ParseCsvLine(lines[0]);

                // Parse data rows
                for (int i = 1; i < lines.Length; i++)
                {
                    if (string.IsNullOrWhiteSpace(lines[i]))
                        continue;

                    var values = ParseCsvLine(lines[i]);
                    var row = new Dictionary<string, string>();

                    for (int j = 0; j < headers.Count && j < values.Count; j++)
                    {
                        row[headers[j]] = values[j];
                    }

                    var element = IfcElementData.FromCsvRow(row);
                    elements.Add(element);
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"Error parsing CSV file: {e.Message}");
            }

            return elements;
        }

        /// <summary>
        /// Parse a single CSV line handling quoted fields.
        /// </summary>
        private static List<string> ParseCsvLine(string line)
        {
            var result = new List<string>();
            var currentField = new StringBuilder();
            bool inQuotes = false;

            for (int i = 0; i < line.Length; i++)
            {
                char c = line[i];

                if (c == '"')
                {
                    if (inQuotes && i + 1 < line.Length && line[i + 1] == '"')
                    {
                        // Escaped quote
                        currentField.Append('"');
                        i++;
                    }
                    else
                    {
                        inQuotes = !inQuotes;
                    }
                }
                else if (c == ',' && !inQuotes)
                {
                    result.Add(currentField.ToString().Trim());
                    currentField.Clear();
                }
                else
                {
                    currentField.Append(c);
                }
            }

            result.Add(currentField.ToString().Trim());
            return result;
        }

        /// <summary>
        /// Build spatial hierarchy from element data.
        /// </summary>
        public static IfcSpatialHierarchy BuildSpatialHierarchy(List<IfcElementData> elements)
        {
            var hierarchy = new IfcSpatialHierarchy();

            // Find project
            var projectElement = elements.FirstOrDefault(e => e.IfcClass == "IfcProject");
            hierarchy.ProjectName = projectElement?.Name ?? "IFC Project";

            // Group elements by Site > Building > Storey
            var siteGroups = elements
                .Where(e => !string.IsNullOrEmpty(e.Site) || e.IfcClass == "IfcSite")
                .GroupBy(e => e.Site);

            foreach (var siteGroup in siteGroups)
            {
                var siteElement = elements.FirstOrDefault(e => e.IfcClass == "IfcSite" && e.Name == siteGroup.Key);
                var siteNode = new IfcSiteNode
                {
                    GlobalId = siteElement?.GlobalId ?? Guid.NewGuid().ToString(),
                    Name = siteGroup.Key ?? "Default Site"
                };

                // Group by building
                var buildingGroups = siteGroup
                    .Where(e => !string.IsNullOrEmpty(e.Building) || e.IfcClass == "IfcBuilding")
                    .GroupBy(e => e.Building);

                foreach (var buildingGroup in buildingGroups)
                {
                    var buildingElement = elements.FirstOrDefault(e => e.IfcClass == "IfcBuilding" && e.Name == buildingGroup.Key);
                    var buildingNode = new IfcBuildingNode
                    {
                        GlobalId = buildingElement?.GlobalId ?? Guid.NewGuid().ToString(),
                        Name = buildingGroup.Key ?? "Default Building"
                    };

                    // Group by storey
                    var storeyGroups = buildingGroup
                        .Where(e => !e.IsSpatialElement())
                        .GroupBy(e => e.Storey);

                    foreach (var storeyGroup in storeyGroups)
                    {
                        var storeyElement = elements.FirstOrDefault(e => e.IfcClass == "IfcBuildingStorey" && e.Name == storeyGroup.Key);
                        var storeyNode = new IfcStoreyNode
                        {
                            GlobalId = storeyElement?.GlobalId ?? Guid.NewGuid().ToString(),
                            Name = storeyGroup.Key ?? "Unassigned"
                        };

                        storeyNode.ElementIds = storeyGroup.Select(e => e.GlobalId).ToList();
                        buildingNode.Storeys.Add(storeyNode);
                    }

                    siteNode.Buildings.Add(buildingNode);
                }

                hierarchy.Sites.Add(siteNode);
            }

            // Handle elements without site assignment
            var unassignedElements = elements
                .Where(e => string.IsNullOrEmpty(e.Site) && !e.IsSpatialElement())
                .ToList();

            if (unassignedElements.Any())
            {
                var defaultSite = hierarchy.Sites.FirstOrDefault(s => s.Name == "Default Site");
                if (defaultSite == null)
                {
                    defaultSite = new IfcSiteNode
                    {
                        GlobalId = Guid.NewGuid().ToString(),
                        Name = "Default Site"
                    };
                    hierarchy.Sites.Add(defaultSite);
                }

                var defaultBuilding = defaultSite.Buildings.FirstOrDefault(b => b.Name == "Default Building");
                if (defaultBuilding == null)
                {
                    defaultBuilding = new IfcBuildingNode
                    {
                        GlobalId = Guid.NewGuid().ToString(),
                        Name = "Default Building"
                    };
                    defaultSite.Buildings.Add(defaultBuilding);
                }

                var storeyGroups = unassignedElements.GroupBy(e => e.Storey);
                foreach (var storeyGroup in storeyGroups)
                {
                    var storeyName = string.IsNullOrEmpty(storeyGroup.Key) ? "Unassigned" : storeyGroup.Key;
                    var storeyNode = defaultBuilding.Storeys.FirstOrDefault(s => s.Name == storeyName);

                    if (storeyNode == null)
                    {
                        storeyNode = new IfcStoreyNode
                        {
                            GlobalId = Guid.NewGuid().ToString(),
                            Name = storeyName
                        };
                        defaultBuilding.Storeys.Add(storeyNode);
                    }

                    storeyNode.ElementIds.AddRange(storeyGroup.Select(e => e.GlobalId));
                }
            }

            return hierarchy;
        }

        /// <summary>
        /// Get element class statistics.
        /// </summary>
        public static Dictionary<string, int> GetElementClassCounts(List<IfcElementData> elements)
        {
            return elements
                .Where(e => !e.IsSpatialElement())
                .GroupBy(e => e.IfcClass)
                .ToDictionary(g => g.Key, g => g.Count());
        }

        /// <summary>
        /// Get element storey statistics.
        /// </summary>
        public static Dictionary<string, int> GetElementStoreyCounts(List<IfcElementData> elements)
        {
            return elements
                .Where(e => !e.IsSpatialElement())
                .GroupBy(e => string.IsNullOrEmpty(e.Storey) ? "Unassigned" : e.Storey)
                .ToDictionary(g => g.Key, g => g.Count());
        }
    }
}
